INFO: pip is looking at multiple versions of ollama to determine which version is compatible with other requirements. This could take a while. ERROR: Cannot install -r requirements.txt (line 12), -r requirements.txt (line 7) and httpx==0.28.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested httpx==0.28.1
    chromadb 0.5.23 depends on httpx>=0.27.0
    ollama 0.4.5 depends on httpx<0.28.0 and >=0.27.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts